config/routes.rb
Rails.application.routes.draw do
  root 'todos#index'
  post 'todos',:to=>'todos#create'
  get 'todos/:id', to: 'todos#destroy'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
    def get_data
        "#{task} #{date_task} #{status} #{create_at.to_date}"
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  def index
    @todo = Todo.new
    @show_data = Todo.all.map do |todolist|
      todolist
    end
    @show_data
  end
  def create
    new_todo = Todo.new(todo_params)
    if new_todo.save
      redirect_to root_path
      # render plain: "Success"
    #  render "todos/index"
    else
      render plain:"Unsuccess"
    end
  end
  # def get_data
  # puts data =  new_todo.all
  # end
  def todo_params
      params.require(:todo).permit(:task,:date_task)
  end
  def destroy
    # @delete = Todo.find(params[:id])
    @todos = Todo.find(params[:id])
     @todos.destroy
    # flash[:success] = "The to-do item was successfully destroyed."
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todo_con_helper.rb
module TodoConHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoProject</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/todos/index.html.erb
<%# <h1>TodoCon#index</h1>
<p>Find me in app/views/todo_con/index.html.erb</p>
<h1>Welcome to index page</h1> %>


<style>
/* * {
	padding: 0;
	margin: 0;
	box-sizing: border-box;
	font-family: cursive;
} */

body {
	background: #f2f2f2;
	overflow: auto;
}

h1{
	text-align: center;
	margin: 5%;
	font-size: 3rem;
	text-decoration: underline;
}
/* h1:hover {
  background-color: violet;
} */

ul {
	text-align: left;
	padding-left: 10%;
	padding: 7%;
	font-size: 2rem;
	list-style: circle;
}
#myInput{
	/* padding-left: 10%; */
	margin-left:20%;
	margin-top:5%;
	padding:2%;
	font-size:20px;
}
.row{
border:5px black solid;
width:50%;
height:50vh;
margin-left:25%;
}
.date{
	padding:2%;
}
.Btn{
padding:2%;	
}
li:hover{
	color:red;
	margin: 4%;
	transition: 1.5s ease;
	cursor: pointer;
}
.tasklist{
	margin-left:20%;
	/* margin-top:1%; */
	
}

</style>

	<div class="container">
		<h1 class="">
		&nbsp;&nbsp;&nbsp;
		TODO APP
		&nbsp;&nbsp;&nbsp;
		</h1>
		<br/><br/>
		<div class="row">
		

			<%# <form class="form-inline col-sm-offset-3"> %>
			<%= form_with(model: @todo,  url: "/todos", method: "POST") do |form| %>
			  <%= form.text_field :task, id:"myInput",placeholder: "Add a Task...",class: "form-control", :required => true  %>
			  <%= form.date_field :date_task, id: "myDueDate", class: "date" ,:required => true  %>
			  <%= form.submit "Add Task", class:"Btn" %>
			<% end %>
			<% @show_data.each do |record| %>
			<h2 class = "tasklist"><%=record.task %> &nbsp  &nbsp &nbsp <%=record.date_task %>
			
			<%=  link_to "Delete", "/todos/#{record.id}", :data => {:confirm => 'Are you sure?'} %> 
			</h2>
			<%# <p>
			<%  link_to "Delete", todos_path(record) , :confirm =>"Are you sure?", :method => :delete %></p> 
			<%# <input type="button" class="Delete" value="Delete"> %>
			<% end %>
				
		</div>
		
	</div>